server:
  port: 8761
spring:
  application:
    name: health-handler-server
eureka:
  instance:
    hostname: localhost
    metadata-map:
      name: jixs
  client:
    registerWithEureka: false
    fetchRegistry: false
    registry-fetch-interval-seconds:

