server:
  port: 8761

spring:
  application:
    name: cluster-servers
  profiles: slavel

eureka:
  instance:
    hostname: slavel
  client:
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
      # 表示是否注册自身到eureka服务器
    register-with-eureka: false
      # 是否从eureka上获取注册信息
    fetch-registry: false

---
server:
  port: 8762

spring:
  application:
    name: cluster-servers
  profiles: slave2

eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://slavel:8761/eureka/
      # 表示是否注册自身到eureka服务器
    register-with-eureka: false
      # 是否从eureka上获取注册信息
    fetch-registry: false