server:
  port: 9000

spring:
  application:
    name: cloud-invoker
  cloud:
    loadbalancer:
      retry:
        enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


cloud-provider:
  ribbon:
    NFLoadBalancerRuleClassName: org.crazyit.cloud.ProviderChooseRule
    NFLoadBalancerPingClassName: org.crazyit.cloud.ProviderPing
    listOfServers: http://localhost:8080/,http://localhost:8081/